#define PC_UNDEFINED	0 
#define PC_SCOUT		1 
#define PC_SNIPER		2 
#define PC_SOLDIER		3 
#define PC_DEMOMAN		4 
#define PC_MEDIC		5 
#define PC_HVYWEAP		6 
#define PC_PYRO			7
#define PC_SPY			8
#define PC_ENGINEER		9
#define PC_RANDOM		10 	
#define PC_CIVILIAN		11
#define PC_LASTCLASS	12

#define WEAPON_HOOK					1
#define WEAPON_BIOWEAPON			(WEAPON_HOOK + 1)
#define WEAPON_MEDIKIT				(WEAPON_HOOK + 2)
#define WEAPON_SPANNER				(WEAPON_HOOK + 3)
#define WEAPON_AXE					(WEAPON_HOOK + 4)
#define WEAPON_SNIPER_RIFLE			(WEAPON_HOOK + 5)
#define WEAPON_AUTO_RIFLE			(WEAPON_HOOK + 6)
#define WEAPON_TF_SHOTGUN			(WEAPON_HOOK + 7)
#define WEAPON_SUPER_SHOTGUN		(WEAPON_HOOK + 8)
#define WEAPON_NAILGUN				(WEAPON_HOOK + 9)
#define WEAPON_SUPER_NAILGUN		(WEAPON_HOOK + 10)
#define WEAPON_GRENADE_LAUNCHER		(WEAPON_HOOK + 11)
#define WEAPON_FLAMETHROWER			(WEAPON_HOOK + 12)
#define WEAPON_ROCKET_LAUNCHER		(WEAPON_HOOK + 13)
#define WEAPON_INCENDIARY			(WEAPON_HOOK + 14)
#define WEAPON_ASSAULT_CANNON		(WEAPON_HOOK + 16)
#define WEAPON_LIGHTNING			(WEAPON_HOOK + 17)
#define WEAPON_DETPACK				(WEAPON_HOOK + 18)
#define WEAPON_TRANQ				(WEAPON_HOOK + 19)
#define WEAPON_LASER				(WEAPON_HOOK + 20)
#define WEAPON_PIPEBOMB_LAUNCHER	(WEAPON_HOOK + 21)
#define WEAPON_KNIFE				(WEAPON_HOOK + 22)
#define WEAPON_BENCHMARK			(WEAPON_HOOK + 23)